// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdJoQ7UwhD696zRxC8IODdn91UXothYro',
    appId: '1:260623790963:web:99c7021548bc6826c48b06',
    messagingSenderId: '260623790963',
    projectId: 'proyecto1-6354a',
    authDomain: 'proyecto1-6354a.firebaseapp.com',
    storageBucket: 'proyecto1-6354a.firebasestorage.app',
    measurementId: 'G-XT6EYHLN4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjyknRnOJuBUWJOV4t86k70dPTTz8HG2A',
    appId: '1:260623790963:android:554eb86c2674d492c48b06',
    messagingSenderId: '260623790963',
    projectId: 'proyecto1-6354a',
    storageBucket: 'proyecto1-6354a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGlcEmrnR8LQdIHi0jbFIlvisSOg7Xjs',
    appId: '1:260623790963:ios:f2f5613e6cad893cc48b06',
    messagingSenderId: '260623790963',
    projectId: 'proyecto1-6354a',
    storageBucket: 'proyecto1-6354a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGlcEmrnR8LQdIHi0jbFIlvisSOg7Xjs',
    appId: '1:260623790963:ios:f2f5613e6cad893cc48b06',
    messagingSenderId: '260623790963',
    projectId: 'proyecto1-6354a',
    storageBucket: 'proyecto1-6354a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdJoQ7UwhD696zRxC8IODdn91UXothYro',
    appId: '1:260623790963:web:ac7476358783b308c48b06',
    messagingSenderId: '260623790963',
    projectId: 'proyecto1-6354a',
    authDomain: 'proyecto1-6354a.firebaseapp.com',
    storageBucket: 'proyecto1-6354a.firebasestorage.app',
    measurementId: 'G-NZZMF6W4WE',
  );
}
